version: 2

updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: daily
      cooldown:
          default-days: 5
      commit-message:
          prefix: 'build(deps):'
