import * as React from 'react'

import { act, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { axe } from 'jest-axe'

import { Box } from '../box'
import { Button } from '../button'
import { flushMicrotasks } from '../utils/test-helpers'

import { Tooltip } from './tooltip'

describe('Tooltip', () => {
    it('renders a tooltip when the button gets focus, hides it when blurred', async () => {
        render(
            <Tooltip content="tooltip content here">
                <button>Click me</button>
            </Tooltip>,
        )
        const button = screen.getByRole('button', { name: 'Click me' })

        userEvent.tab()
        expect(button).toHaveFocus()
        expect(
            await screen.findByRole('tooltip', { name: 'tooltip content here' }),
        ).toBeInTheDocument()

        userEvent.tab()

        // TODO: Works in the browser, but not in the test
        // await waitFor(() => {
        //     expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
        // })
    })

    it('renders a tooltip when the button is hovered, hides it when unhovered', async () => {
        render(
            <Tooltip content="tooltip content here">
                <button>Click me</button>
            </Tooltip>,
        )
        const button = screen.getByRole('button', { name: 'Click me' })

        userEvent.hover(button)
        expect(
            await screen.findByRole('tooltip', { name: 'tooltip content here' }),
        ).toBeInTheDocument()

        userEvent.unhover(button)
        // TODO: Works in the browser, but not in the test
        // await waitFor(() => {
        //     expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
        // })
    })

    it('does not render a tooltip if the content is empty', async () => {
        jest.useFakeTimers()
        render(
            <Tooltip content={null}>
                <button>Click me</button>
            </Tooltip>,
        )
        const button = screen.getByRole('button', { name: 'Click me' })

        // mouse over and wait more than enough
        userEvent.hover(button)
        act(() => {
            jest.advanceTimersByTime(1000)
        })
        expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()

        // focus on button and wait more than enough
        userEvent.tab()
        expect(button).toHaveFocus()
        await act(() => {
            jest.advanceTimersByTime(1000)
            // Ariakit performs state changes asynchronously that needs to be flushed
            return Promise.resolve()
        })

        expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
        jest.useRealTimers()
    })

    it('does not render the tooltip markup at all while not shown', () => {
        render(
            <Tooltip content="tooltip content here">
                <button>Click me</button>
            </Tooltip>,
        )
        // queryByText, unlike getByRole, will find an element even if hidden with display: none or
        // by any other means. getByRole on the other hand takes visibility into account.
        expect(screen.queryByText('tooltip content here')).not.toBeInTheDocument()
    })

    it('can render content generated by a function only called when needed', async () => {
        jest.useFakeTimers()
        const content = jest.fn(() => 'tooltip content generated dynamically')
        render(
            <Tooltip content={content}>
                <button>Click me</button>
            </Tooltip>,
        )
        const button = screen.getByRole('button', { name: 'Click me' })

        // assert that content has not been generated internally even, not even after a delay
        act(() => {
            jest.advanceTimersByTime(1000)
        })
        expect(content).not.toHaveBeenCalled()

        // content is generated when the tooltip is needed to be shown
        userEvent.hover(button)
        act(() => {
            jest.advanceTimersByTime(500)
        })

        // Ariakit performs state changes asynchronously that needs to be flushed
        await flushMicrotasks()

        expect(content).toHaveBeenCalled()
        jest.useRealTimers()
    })

    /**
     * @see https://github.com/ariakit/ariakit/discussions/749
     */
    it('does not show the tooltip if the button received focus in a way not associated with a key event', () => {
        function getTooltipButton() {
            return screen.getByRole('button', { name: 'Click me' })
        }

        render(
            <>
                <Tooltip content="tooltip content here">
                    <button>Click me</button>
                </Tooltip>
                <button onClick={() => getTooltipButton().focus()}>Trigger focus</button>
            </>,
        )

        userEvent.click(screen.getByRole('button', { name: 'Trigger focus' }))
        expect(getTooltipButton()).toHaveFocus()

        act(() => {
            jest.advanceTimersByTime(1000)
        })
        expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    })

    it("does not interfere with the trigger element's ref forwarding", () => {
        const buttonRef = React.createRef<HTMLButtonElement>()

        render(
            <Tooltip content="tooltip content here">
                <button ref={buttonRef}>Click me</button>
            </Tooltip>,
        )

        expect(buttonRef.current).toBe(screen.getByRole('button'))
    })

    it('supports components with an "as" prop as the anchor', async () => {
        render(
            <Tooltip content="tooltip content here">
                <Box as={Button} variant="primary">
                    Click me
                </Box>
            </Tooltip>,
        )

        const button = screen.getByRole('button', { name: 'Click me' })
        expect(button).toBeVisible()

        userEvent.hover(button)
        expect(
            await screen.findByRole('tooltip', { name: 'tooltip content here' }),
        ).toBeInTheDocument()

        userEvent.unhover(button)
        // TODO: Works in the browser, but not in the test
        // await waitFor(() => {
        //     expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
        // })
    })

    describe('a11y', () => {
        it('renders with no a11y violations', async () => {
            const { container } = render(
                <Tooltip content="tooltip content here">
                    <button>Click me</button>
                </Tooltip>,
            )

            const button = screen.getByRole('button', { name: 'Click me' })
            userEvent.hover(button)

            act(() => {
                jest.advanceTimersByTime(1000)
            })

            // Ariakit performs state changes asynchronously that needs to be flushed
            await flushMicrotasks()

            jest.useRealTimers()

            const results = await axe(container)
            expect(results).toHaveNoViolations()
        })
    })

    it('does not acknowledge the className prop, but exceptionallySetClassName instead', async () => {
        render(
            <Tooltip
                content="I’m a tooltip"
                // @ts-expect-error
                className="wrong"
                exceptionallySetClassName="right"
            >
                <button>Click me</button>
            </Tooltip>,
        )
        // Since the content is only rendered when the tooltip appears, this description is only
        // available when we hover or focus the button, and not before.
        userEvent.tab()

        const tooltip = await screen.findByRole('tooltip', { name: 'I’m a tooltip' })
        expect(tooltip).toHaveClass('right')
        expect(tooltip).not.toHaveClass('wrong')
    })
})
