name: Semantic Pull Request

on:
    pull_request:
        types:
            - edited
            - opened
            - synchronize
    push:
        branches:
            - gh-readonly-queue/main/**

jobs:
    validate-title:
        name: Validate Title
        runs-on: ubuntu-latest

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 5
        steps:
            - name: Validate pull request title
              uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
              with:
                  validateSingleCommit: true
