name: 'Chromatic'

on: push

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Prepare Node.js environment
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.node-version'
                  registry-url: https://npm.pkg.github.com
                  scope: '@doist'

            - name: Cache project 'node_modules' directory
              id: node-modules-cache
              uses: actions/cache@v4
              with:
                  key: node-modules-cache-${{ hashFiles('**/package-lock.json', '**/.node-version') }}
                  path: node_modules/

            - name: Install project npm dependencies
              if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Publish to Chromatic
              uses: chromaui/action@d7afd50124cf4f337bcd943e7f45cfa85a5e4476
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  skip: dependabot/**
                  onlyChanged: true
                  buildScriptName: build:storybook
