name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Prepare Node.js environment
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'
            registry-url: https://npm.pkg.github.com
            scope: '@doist'

      - name: Install dependencies
        run: npm install

      - name: Prepare Node.js environment
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'
            registry-url: https://npm.pkg.github.com
            scope: '@doist'

      - name: Install dependencies
        run: npm install
      
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: dependabot/**
          onlyChanged: true
