name: Package Release

on:
    push:
        tags:
            - 'v*'
    # triggered by `release-please.yml`
    workflow_dispatch:

permissions:
    # Enable the use of OIDC for trusted publishing and npm provenance
    id-token: write
    # Enable the use of GitHub Packages registry
    packages: write
    contents: write

jobs:
    publish:
        # Allow both tag pushes and workflow_dispatch events
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        # Based on historical data
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version-file: .node-version

            # Remove any registry configurations from .npmrc
            - run: sed -i "/@doist/d" ./.npmrc

            - run: npm ci
            - run: npm run lint
            - run: npm run type-check
            - run: npm test

            # Build artifacts for publishing
            - run: npm run build

            # Publish to GitHub package registry
            - uses: actions/setup-node@v6
              with:
                  node-version-file: .node-version
                  registry-url: https://npm.pkg.github.com/
                  scope: '@doist'
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            # Publish to npm registry
            - uses: actions/setup-node@v6
              with:
                  node-version-file: .node-version
                  registry-url: https://registry.npmjs.org/
                  scope: '@doist'
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
