name: Release

on:
    push:
        branches:
            - main

permissions:
    # Enable `semantic-release` to publish a GitHub release and push commits
    contents: write
    # Enable `semantic-release` to post comments on issues
    issues: write
    # Enable `semantic-release` to post comments on pull requests
    pull-requests: write
    # Enable the use of OIDC for trusted publishing and npm provenance
    id-token: write
    # Enable the use of GitHub Packages registry
    packages: write

# Release involves crucial steps that shouldn't be cancelled mid-run,
# so new workflow runs are queued until the previous one finishes.
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Generate bot token
              id: generate_token
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ secrets.DOIST_RELEASE_BOT_ID }}
                  private-key: ${{ secrets.DOIST_RELEASE_BOT_PRIVATE_KEY }}

            - name: Get bot user ID
              id: bot_user
              run: echo "id=$(gh api "/users/${{ steps.generate_token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
              env:
                  GH_TOKEN: ${{ steps.generate_token.outputs.token }}

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.generate_token.outputs.token }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version
                  cache: npm
                  scope: '@doist'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: npm ci

            - name: Capture previous tag
              id: previous_tag
              run: echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || true)" >> "$GITHUB_OUTPUT"

            - name: Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
                  GIT_AUTHOR_NAME: ${{ steps.generate_token.outputs.app-slug }}[bot]
                  GIT_AUTHOR_EMAIL: ${{ steps.bot_user.outputs.id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com
                  GIT_COMMITTER_NAME: ${{ steps.generate_token.outputs.app-slug }}[bot]
                  GIT_COMMITTER_EMAIL: ${{ steps.bot_user.outputs.id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com

            - name: Check if release was created
              id: check_release
              env:
                  PREVIOUS_TAG: ${{ steps.previous_tag.outputs.tag }}
              run: |
                  git fetch --force --tags origin
                  new_tag="$(git describe --tags --abbrev=0 2>/dev/null || true)"
                  if [ -z "${new_tag}" ] || [ "${new_tag}" = "${PREVIOUS_TAG}" ]; then
                      echo "released=false" >> "$GITHUB_OUTPUT"
                  else
                      echo "released=true" >> "$GITHUB_OUTPUT"
                  fi

            - name: Remove Doist registry configuration from .npmrc
              if: ${{ steps.check_release.outputs.released == 'true' }}
              run: npm config delete @doist:registry --location=project

            - name: Prepare Node.js environment for GitHub Packages registry
              if: ${{ steps.check_release.outputs.released == 'true' }}
              uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version
                  registry-url: https://npm.pkg.github.com/
                  scope: '@doist'

            - name: Publish package to GitHub Packages registry
              if: ${{ steps.check_release.outputs.released == 'true' }}
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
